version: '3'
services:
  db:
    image: postgres
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/emr-blog
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
